### ISSUE TITLE
low level method to sign with ecdsa

### ISSUE THREAD

**Issue by gitzhou** [OneKeyHQ/hardware-js-sdk#281]
Hi team,

I've read the doc about how to sign a BTC transaction https://developer.onekey.so/connect-to-hardware/hardware-sdk/api-reference/bitcoin/btcsigntransaction. It requires passing a struct to describe the transaction

```ts
HardwareSDK.btcSignTransaction(connectId, deviceId, {
    inputs: [
        {
            address_n: [(44 | 0x80000000) >>> 0, (0 | 0x80000000) >>> 0, (2 | 0x80000000) >>> 0, 1, 0],
            prev_index: 0,
            prev_hash: 'b035d89d4543ce5713c553d69431698116a822c57c03ddacf3f04b763d1999ac',
        }
    ],
    outputs: [
        {
            address_n: [(44 | 0x80000000) >>> 0, (0 | 0x80000000) >>> 0, (2 | 0x80000000) >>> 0, 1, 1],
            amount: '3181747',
            script_type: 'PAYTOADDRESS',
        }, {
            address: '18WL2iZKmpDYWk1oFavJapdLALxwSjcSk2',
            amount: '200000',
            script_type: 'PAYTOADDRESS',
        }
    ],
    coin: 'btc'
});
```

I'm wondering if there's a way to call a method to sign with ECDSA, directly passing the `sighashPreimage` instead of a struct tx, so that we can call like

```ts
HardwareSDK.signEcdsa(connectId, deviceId, {
    path: "m/44'/0'/0'",
    sighashPreimage: "xxxxxxxxxx"
});
```

this method would return the result of the DER signature `3045xxxxxxx`, or the raw ECDSA signature (r, s).

Thank you.

**Comment by originalix** [comment]
Unfortunately, we do not currently support this low-level signature method. For Bitcoin signature, the hardware needs to obtain the transaction structure, verify each UTXO, and then sign accordingly.

**Comment by gitzhou** [comment]
Thanks @originalix 

One more question. For a new blockchain that would like to apply for OneKey to support, is there any document or flow that can be referred to?

**Comment by originalix** [comment]
Supporting a new blockchain mainly requires firmware support. I have contacted our BD @Jenny0115 and she will reply this issue later.

**Comment by gitzhou** [comment]
Much appreciated

**Comment by Jenny0115** [comment]
Hi @gitzhou  Would you mind sending an email to Jenny@onekey.so with the information of this new blockchain?

**Comment by originalix** [comment]
I’m going to close this issue for now. Thanks Jenny.
