### ISSUE TITLE
Question about hardware-sdk passphrase flow

### ISSUE THREAD

**Issue by tonzgao** [OneKeyHQ/hardware-js-sdk#282]
I noticed in the passphrase docs that entering the passphrase through keyboard requires the user-facing wallet to request the passphrase from the user https://github.com/OneKeyHQ/docs/blob/main/connect-to-hardware/hardware-sdk/passphrase.md#enter-the-passphrase-in-the-software. This seems incorrect to me, as the purpose of the hardware wallet is to ensure that the user-facing wallet does not know anything about the PIN or passphrase. Shouldn't this be handled by the bridge software instead? This is what Trezor does, for example.

**Comment by originalix** [comment]
Having users input the PIN or Passphrase is just a UX improvement. The obtained result will be handed over to the Bridge software for communication with the hardware wallet. The handling process here is basically the same as with Trezor.

Both ease of input and security are considered factors. Of course, inputting exclusively on the hardware is also completely fine.

**Comment by tonzgao** [comment]
So to elaborate, this is my understanding of the current flow

1. PIN entered
2. Wallet gets passphrase from user
3. Wallet passes passphrase to bridge
4. Bridge passes passphrase to hardware

But an alternate flow (which Trezor does) which seems better to me is:

1. PIN entered
2. Bridge gets passphrase from user
3. Bridge passes passphrase to hardware

The difference here in my proposed flow is that the wallet does not have anything to do with the passphrase and therefore the process is more secure. Do you know what I mean?

**Comment by originalix** [comment]
I understand your concerns, and I think you’re mostly worried about the passphraseState parameter. The purpose of this parameter is to avoid frequent input of the passphrase, so we advise the wallet to appropriately cache this parameter.

However, you can also design the process so there is no caching at all. Instead, you can always get the fresh passphraseState through the `getPassphraseState` API. This passphrase is not returned in plaintext, the wallet layer does not know your real input passphrase.

**Comment by tonzgao** [comment]
So actually I'm not super concerned about passphrase state. I am actually worried about two things

First, exactly what I said which is that the code below expects the user to enter the passphrase into the wallet which is a security risk
```
HardwareSDK.uiResponse({
  type: UI_RESPONSE.RECEIVE_PASSPHRASE,
    payload: {
    value: '${user's passphrase}',
    passphraseOnDevice: true,
    save: true,
   },
});
```

Secondly, that the wallet I currently user (Rabby) does not make use of this flow and it seems unlikely to me that any security minded wallet should or would because of the issue above.

**Comment by originalix** [comment]
We have had a lot of communication with Rabby during the integration process of the HardwareSDK. As far as I know, they simply don’t have extra resources to handle UI-level input at the moment.

Of course, I totally agree with your statement that entering a PIN or passphrase on the software level might pose a potential security risk, For example, data could be tampered with by a trojan horse at the Bridge layer. 

That’s why the latest OneKey Touch device does not support input on the software side at all. Currently, only Classic and Mini devices support software-side input.

Additionally, you can take a look at the [Trezor wallet’s source code](https://github.com/trezor/trezor-suite/blob/40b035b2be45a4792adc9fb8373fdacff7b89bb3/packages/suite/src/actions/suite/modalActions.ts#L59) - the PIN and passphrase are returned the same way at the software level.

**Comment by tonzgao** [comment]
Yes, that's through Trezor suite. When it's through rabby or metamask it is handled by the bridge software, in the proposed flow I described earlier. So you consider this a non-issue?

The reason I'm asking is my passphrase is rather inconvenient to enter on hardware and I bought the onekey originally for USB-C. As you know, Trezor recently launched their new model with USB-C.

**Comment by originalix** [comment]
Yes, sometimes user experience is achieved at the sacrifice of some security aspects. Therefore, even in the OneKey client, we offer options to enter the PIN and Passphrase on the device itself.

Thank you for your feedback. We have updated our documents to indicate that we do not recommend entering the passphrase on the software end. I’ll be closing this issue for now, but feel free to continue the conversation if further questions arise.
